import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import GNB from "@/components/GNB";
import { ThemeProvider } from "@/components/ThemeProvider";
import SideMenu from "@/components/SideMenu";
import GoogleLoginProvider from "@/components/GoogleLoginProvier";
import { Toaster } from "@/components/ui/sonner";
import { cookies } from "next/headers";

const pretendard = localFont({
  src: "../assets/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * 다크 모드를 켤려면 default = 'system', enableSystem = true로 설정해주세요.
 *
 * text-disable-1 = text-white/50
 * text-disable-2 = text-white/30
 */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const isLogin = cookieStore.get("auth-token");

  return (
    <html lang='ko' suppressHydrationWarning>
      <body className={`bg-side ${pretendard.className} antialiased`}>
        <GoogleLoginProvider>
          <ThemeProvider attribute='class' defaultTheme='light' enableSystem={false} disableTransitionOnChange>
            <div className='relative flex flex-col min-h-screen mx-auto max-w-[600px] min-h-screen bg-background'>
              <SideMenu isLogin={isLogin ? true : false} />
              {children}
              <GNB />
            </div>
            <Toaster position='top-center' visibleToasts={1} richColors toastOptions={{ duration: 2000 }} />
          </ThemeProvider>
        </GoogleLoginProvider>
      </body>
    </html>
  );
}
