import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import GNB from "@/components/GNB";
import { ThemeProvider } from "@/components/ThemeProvider";
import SideMenu from "@/components/SideMenu";

const pretendard = localFont({
  src: "../assets/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * 다크 모드를 켤려면 default = 'system', enableSystem = true로 설정해주세요.
 */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko' suppressHydrationWarning>
      <body className={`bg-side ${pretendard.className} antialiased`}>
        <ThemeProvider attribute='class' defaultTheme='light' enableSystem={false} disableTransitionOnChange>
          <div className='relative flex flex-col min-h-screen mx-auto w-[600px] min-h-screen bg-background'>
            <SideMenu />
            <GNB />
            <main className='flex-1'>{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
